/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: LasquetiSpice (https://sketchfab.com/LasquetiSpice)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/archer-shooting-arrow-from-bow-in-battle-56ef54cd228e45e1928ed2cf441131ff
title: Archer Shooting Arrow from Bow in Battle
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/archer.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.65}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes._rootJoint} />
          <mesh geometry={nodes.Erika_Archer_Arrow_Mesh_Arrow_MAT_0.geometry} material={materials.Arrow_MAT} />
          <skinnedMesh
            geometry={nodes.Object_6.geometry}
            material={materials.Bow_MAT}
            skeleton={nodes.Object_6.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_7.geometry}
            material={materials.Akai_MAT}
            skeleton={nodes.Object_7.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_8.geometry}
            material={materials.EyeSpec_MAT}
            skeleton={nodes.Object_8.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_9.geometry}
            material={materials.Lashes_MAT}
            skeleton={nodes.Object_9.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_10.geometry}
            material={materials.Body_MAT}
            skeleton={nodes.Object_10.skeleton}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/archer.gltf')
